Update with Comp 40 details
tekknolagi/tuftscs-tips pull request #1
Opened 2017-01-18 17:00 UTC by GrahamGoudeau

2017-01-18 18:15 UTC, tekknolagi requested changes
Awesome job. Couple changes if possible

2017-01-18 18:15 UTC, tekknolagi commented on README.md
> +* Become acquainted with sites that contain documentation and Q&A resources, such as Stack Overflow and [Tutorials Point](https://www.tutorialspoint.com/cprogramming/).  I'm not sure how well-regarde
Avoid first person if possible

2017-01-18 18:15 UTC, tekknolagi commented on README.md
> +* Learn effective Googling strategies.  For example, googling `site:stackoverflow.com sscanf` will limit your search results to Stack Overflow.
Is this more of a tip or extending core material?

2017-01-18 18:15 UTC, tekknolagi commented on README.md
> +* Explore compilation (look for links in the [COMP 105](#comp-105) section.
Dropped paren

2017-01-18 18:15 UTC, tekknolagi commented on README.md
> +### Other related material
Perhaps also writing your own VM, etc

2017-01-18 18:15 UTC, tekknolagi commented on README.md
> +### Other related material
Also optimization

2017-01-18 18:15 UTC, tekknolagi commented on README.md
> +### Tufts resources
Noah!

2017-01-19 07:10 UTC, tekknolagi commented on README.md
> +  * Implement various collections (hash tables, sets, etc.)
*cough* COMP 15 *cough cough*

2017-01-19 15:12 UTC, GrahamGoudeau commented on README.md
> +  * Implement various collections (hash tables, sets, etc.)
I'm going to leave these in.  I think that it's a good exercise in familiarizing yourself with C idioms.  You can get a good feel for things like void pointers with implementing these collections in C, whereas you might use templates (or just implement monomorphic collections) in 15.

2017-01-19 15:12 UTC, GrahamGoudeau commented on README.md
> +### Tufts resources
Not sure how I forgot him- oops

2017-01-19 15:12 UTC, GrahamGoudeau commented on README.md
> +### Other related material
yep

2017-01-19 15:13 UTC, GrahamGoudeau commented on README.md
> +* Explore compilation (look for links in the [COMP 105](#comp-105) section.
fixed

2017-01-19 15:13 UTC, GrahamGoudeau commented on README.md
> +* Learn effective Googling strategies.  For example, googling `site:stackoverflow.com sscanf` will limit your search results to Stack Overflow.
More of a tip. Moved

2017-01-19 15:13 UTC, GrahamGoudeau commented on README.md
> +* Become acquainted with sites that contain documentation and Q&A resources, such as Stack Overflow and [Tutorials Point](https://www.tutorialspoint.com/cprogramming/).  I'm not sure how well-regarde
Avoided

2017-01-19 16:58 UTC, tekknolagi commented on README.md
> +  * Implement various collections (hash tables, sets, etc.)
ok, fair

2017-01-19 16:59 UTC, tekknolagi requested changes

2017-01-19 16:59 UTC, tekknolagi commented on README.md
>  * As long as you try your best during the class, the points will work themselves out in the end. That's why we give vague grades like "Very good", "good", etc.  Don't worry too much about your grades
First person plural -- "the staff"?

2017-01-19 17:25 UTC, tekknolagi commented on README.md
>  * As long as you try your best during the class, the points will work themselves out in the end. That's why we give vague grades like "Very good", "good", etc.  Don't worry too much about your grades
Er, not sure if I commented on the right thing.

2017-01-19 17:30 UTC, tekknolagi requested changes

2017-01-19 17:30 UTC, tekknolagi commented on README.md
> +* As long as you try your best during the class, the points will work themselves out in the end. That's why we give vague grades like "Very good", "good", etc.  Don't worry too much about your grades
Ah, this is what I meant. "we give", etc

2017-01-19 17:40 UTC, tekknolagi commented
Merged.

2017-01-19 17:40 UTC, closed without merging